# Generated by Django 2.0.7 on 2018-11-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181110_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Language used in a book', max_length=100),
        ),
    ]
